<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PropelIQ.Modules.ClinicalIntelligence.Domain\PropelIQ.Modules.ClinicalIntelligence.Domain.csproj" />
    <ProjectReference Include="..\PropelIQ.Modules.ClinicalIntelligence.Application\PropelIQ.Modules.ClinicalIntelligence.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
