using PropelIQ.SharedKernel;

namespace PropelIQ.Modules.SharedServices.Domain.Entities;

/// <summary>
/// Compiled disclosure report generated by <c>DisclosureCompilationWorker</c>
/// for a patient's data-access disclosure request (US_057, AC-2, edge case 1).
///
/// The <see cref="ReportJson"/> JSONB column stores the full structured report.
/// A time-limited HMAC-signed <see cref="DownloadToken"/> is attached on approval
/// and presented to the patient as a 48-hour secure download link (AC-3).
/// </summary>
public sealed class DisclosureReport : BaseEntity
{
    /// <summary>FK to the disclosure request that produced this report.</summary>
    public required Guid DisclosureRequestId { get; set; }

    /// <summary>
    /// Serialised JSON document containing the full list of access events.
    /// Stored as PostgreSQL JSONB for compression and integrity.
    /// </summary>
    public required string ReportJson { get; set; }

    /// <summary>Total number of access events included in the report.</summary>
    public required int AccessEventCount { get; set; }

    /// <summary>HMAC-SHA256 signed token granting download access. Set on approval.</summary>
    public string? DownloadToken { get; set; }

    /// <summary>UTC expiry of the download token (48 hours from generation). Null until approval.</summary>
    public DateTimeOffset? DownloadExpiresAt { get; set; }

    /// <summary>Navigation back to the parent request.</summary>
    public DisclosureRequest? Request { get; set; }
}
