// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PropelIQ.Modules.SharedServices.Infrastructure.Data;

#nullable disable

namespace PropelIQ.Modules.SharedServices.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.InsuranceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("member_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payer_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_insurance_profiles");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_insurance_profiles_patient_id");

                    b.ToTable("insurance_profiles", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MRN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mrn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("MRN")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_mrn");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_user_id");

                    b.ToTable("patients", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extraction_status");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clinical_documents");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_documents_patient_id");

                    b.ToTable("clinical_documents", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fact_type");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<Guid?>("LastReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_reviewed_by_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_clinical_facts");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_clinical_facts_document_id");

                    b.ToTable("clinical_facts", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.CodingDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code_type");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FinalizedCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("finalized_code");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reviewer_action");

                    b.Property<string>("SuggestedCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("suggested_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_coding_decisions");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_coding_decisions_document_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_coding_decisions_patient_id");

                    b.ToTable("coding_decisions", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("appointment_type");

                    b.Property<bool>("ArtifactsGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("artifacts_generated");

                    b.Property<DateTimeOffset?>("ArtifactsGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("artifacts_generated_at");

                    b.Property<DateTimeOffset>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ConfirmationCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("confirmation_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("EmailRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("email_retry_count");

                    b.Property<bool>("EmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_sent");

                    b.Property<string>("IcsStoragePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ics_storage_path");

                    b.Property<Guid?>("IntakeRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("intake_record_id");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PdfStoragePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pdf_storage_path");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_name");

                    b.Property<string>("QrCodeStoragePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("qr_code_storage_path");

                    b.Property<string>("QueueState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("queue_state");

                    b.Property<double?>("RiskConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("risk_confidence");

                    b.Property<string>("RiskFeatures")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_features");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<DateTimeOffset?>("RiskScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("risk_scored_at");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<int>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sequence_number");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<Guid?>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("ConfirmationCode")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_confirmation_code")
                        .HasFilter("confirmation_code IS NOT NULL");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("RiskScoredAt")
                        .HasDatabaseName("ix_appointments_risk_scored_at");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_slot_id")
                        .HasFilter("slot_id IS NOT NULL");

                    b.HasIndex("StaffUserId")
                        .HasDatabaseName("ix_appointments_staff_user_id");

                    b.HasIndex("PatientId", "ScheduledAt", "Status")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_appointments_patient_scheduled_status");

                    b.ToTable("appointments", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.AppointmentAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_override");

                    b.Property<Guid?>("NewSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_slot_id");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid?>("PreviousSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_slot_id");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_appointment_audit_entries");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_appointment_audit_appointment_id");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("ix_appointment_audit_performed_at");

                    b.ToTable("appointment_audit_entries", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentBookings")
                        .HasColumnType("integer")
                        .HasColumnName("current_bookings");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_appointment_slots");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_appointment_slots_provider_id");

                    b.HasIndex("StartTime", "Type", "Duration")
                        .HasDatabaseName("ix_appointment_slots_starttime_type_duration");

                    b.ToTable("appointment_slots", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.DeadLetterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("Reprocessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reprocessed");

                    b.Property<Guid>("SourceReminderId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_reminder_id");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("total_attempts");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_dead_letter_events");

                    b.HasIndex("Reprocessed")
                        .HasDatabaseName("ix_dead_letter_events_reprocessed")
                        .HasFilter("\"Reprocessed\" = false");

                    b.HasIndex("SourceReminderId")
                        .HasDatabaseName("ix_dead_letter_events_source_reminder");

                    b.ToTable("dead_letter_events", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.IntakeDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<string>>("AiPopulatedFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_populated_fields");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<JsonDocument>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_intake_drafts");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_intake_drafts_expires_at");

                    b.HasIndex("PatientId", "SlotId", "Status")
                        .HasDatabaseName("ix_intake_drafts_patient_slot_status");

                    b.ToTable("intake_drafts", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.IntakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<string>>("AiPopulatedFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_populated_fields");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("FormData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_intake_records");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_records_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_intake_records_patient_id");

                    b.ToTable("intake_records", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.ReminderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel");

                    b.Property<string>("ConfirmationResponse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("confirmation_response");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SendStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("send_status");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reminder_events");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_events_idempotency_key");

                    b.HasIndex("AppointmentId", "SendStatus")
                        .HasDatabaseName("ix_reminder_events_appointment_send_status");

                    b.HasIndex("SendStatus", "ScheduledAt")
                        .HasDatabaseName("ix_reminder_events_pending_scheduled_at")
                        .HasFilter("\"SendStatus\" = 'Pending'");

                    b.ToTable("reminder_events", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.SlotTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DefaultDuration")
                        .HasColumnType("integer")
                        .HasColumnName("default_duration");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_capacity");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_slot_templates");

                    b.HasIndex("DayOfWeek", "Type", "IsActive")
                        .HasDatabaseName("ix_slot_templates_dayofweek_type_isactive");

                    b.ToTable("slot_templates", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<string>("ClaimTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("claim_token_hash");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset?>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<Guid?>("OfferedSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("offered_slot_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("PreferredAppointmentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preferred_appointment_type");

                    b.Property<DateTimeOffset>("PreferredDateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_date_end");

                    b.Property<DateTimeOffset>("PreferredDateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_date_start");

                    b.Property<int>("PreferredDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_duration_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_waitlist_entries");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_waitlist_entries_appointment_id");

                    b.HasIndex("ClaimExpiresAt")
                        .HasDatabaseName("ix_waitlist_entries_claim_expires_at_offered")
                        .HasFilter("\"Status\" = 'Offered' AND \"ClaimExpiresAt\" IS NOT NULL");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_waitlist_entries_patient_id");

                    b.HasIndex("Status", "ClaimExpiresAt")
                        .HasDatabaseName("ix_waitlist_entries_status_claim_expires_at");

                    b.HasIndex("Status", "Position")
                        .HasDatabaseName("ix_waitlist_entries_status_position");

                    b.ToTable("waitlist_entries", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.SharedServices.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entity_id");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_entity_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_records");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_records_actor_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_records_occurred_at");

                    b.ToTable("audit_records", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.SharedServices.Domain.Entities.EmbeddingSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ContentRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("content_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.HasKey("Id")
                        .HasName("pk_embedding_samples");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_embedding_samples_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("embedding_samples", "app");
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.InsuranceProfile", b =>
                {
                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.Patient", "Patient")
                        .WithMany("InsuranceProfiles")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_insurance_profiles_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.Patient", b =>
                {
                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("PropelIQ.Modules.Administration.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_user_id");

                    b.OwnsOne("PropelIQ.Modules.Administration.Domain.Entities.ContactPreferences", "ContactPreferences", b1 =>
                        {
                            b1.Property<Guid>("PatientId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("EmailEnabled")
                                .HasColumnType("boolean");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PreferredPhone")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("ReminderTimings")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<bool>("SmsEnabled")
                                .HasColumnType("boolean");

                            b1.HasKey("PatientId");

                            b1.ToTable("patients", "app");

                            b1
                                .ToJson("contact_preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PatientId")
                                .HasConstraintName("fk_patients_patients_id");
                        });

                    b.Navigation("ContactPreferences")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalDocument", b =>
                {
                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_documents_patients_patient_id");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalFact", b =>
                {
                    b.HasOne("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany("ClinicalFacts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_facts_clinical_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.CodingDecision", b =>
                {
                    b.HasOne("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coding_decisions_clinical_documents_document_id");

                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coding_decisions_patients_patient_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_appointments_users_staff_user_id");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.ReminderEvent", b =>
                {
                    b.HasOne("PropelIQ.Modules.Scheduling.Domain.Entities.Appointment", "Appointment")
                        .WithMany("ReminderEvents")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_events_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.WaitlistEntry", b =>
                {
                    b.HasOne("PropelIQ.Modules.Scheduling.Domain.Entities.Appointment", "Appointment")
                        .WithOne("WaitlistEntry")
                        .HasForeignKey("PropelIQ.Modules.Scheduling.Domain.Entities.WaitlistEntry", "AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_waitlist_entries_appointments_appointment_id");

                    b.HasOne("PropelIQ.Modules.Administration.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_waitlist_entries_patients_patient_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("PropelIQ.Modules.SharedServices.Domain.Entities.AuditRecord", b =>
                {
                    b.OwnsOne("PropelIQ.Modules.SharedServices.Domain.Entities.AuditDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("AuditRecordId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("ChangeDescription")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("IpAddress")
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.HasKey("AuditRecordId");

                            b1.ToTable("audit_records", "app");

                            b1
                                .ToJson("details")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AuditRecordId")
                                .HasConstraintName("fk_audit_records_audit_records_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.Patient", b =>
                {
                    b.Navigation("InsuranceProfiles");
                });

            modelBuilder.Entity("PropelIQ.Modules.Administration.Domain.Entities.User", b =>
                {
                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("PropelIQ.Modules.ClinicalIntelligence.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Navigation("ClinicalFacts");
                });

            modelBuilder.Entity("PropelIQ.Modules.Scheduling.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("ReminderEvents");

                    b.Navigation("WaitlistEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
