using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PropelIQ.Modules.Scheduling.Application.Booking.Artifacts;
using PropelIQ.Modules.Scheduling.Application.Booking.Dto;
using PropelIQ.Modules.Scheduling.Infrastructure.Booking;
using PropelIQ.SharedKernel;

namespace PropelIQ.Api.Controllers;

/// <summary>
/// Booking creation API.
///
/// POST /api/v1/bookings — atomically reserve a slot and create an appointment (AC-1).
/// GET  /api/v1/bookings/{id} — retrieve a confirmed appointment by ID.
///
/// AC-4: concurrent booking race → HTTP 409 with next available slot suggestion.
/// NFR-010: all operations auditable via AppDbContext SaveChanges interceptors.
/// </summary>
[Authorize]
public sealed class BookingsController : BaseApiController
{
    private readonly BookingService _bookingService;

    public BookingsController(BookingService bookingService)
        => _bookingService = bookingService;

    private Guid GetPatientId() =>
        Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);

    /// <summary>
    /// Atomically reserve a slot and create a confirmed appointment (AC-1).
    /// Returns 201 Created with <see cref="BookingResponse"/> on success.
    /// Returns 409 Conflict with <see cref="SlotConflictResponse"/> when the
    /// slot is taken by a concurrent request before this one commits (AC-4).
    /// </summary>
    /// <response code="201">Booking created — includes confirmation code and appointment details.</response>
    /// <response code="400">Validation failure — SlotId or IntakeRecordId missing/empty.</response>
    /// <response code="401">JWT bearer token missing or invalid.</response>
    /// <response code="409">Slot no longer available — includes next available slot (AC-4).</response>
    [HttpPost]
    [ProducesResponseType(typeof(BookingResponse), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(SlotConflictResponse), StatusCodes.Status409Conflict)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> CreateBooking(
        [FromBody] CreateBookingRequest request,
        CancellationToken ct)
    {
        var (isSuccess, success, conflict) =
            await _bookingService.CreateBookingAsync(GetPatientId(), request, ct);

        if (isSuccess)
        {
            return CreatedAtAction(
                nameof(GetBooking),
                new { id = success!.AppointmentId },
                success);
        }

        // AC-4: concurrent booking conflict — suggest the next available slot.
        return Conflict(conflict);
    }

    /// <summary>
    /// Retrieve a confirmed appointment by its ID.
    /// </summary>
    /// <response code="200">Appointment details returned.</response>
    /// <response code="401">JWT bearer token missing or invalid.</response>
    /// <response code="404">Appointment not found.</response>
    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(BookingResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public Task<IActionResult> GetBooking(Guid id, CancellationToken ct)
    {
        // Full retrieval implementation belongs to a query-side service (task_002 / CQRS).
        // Placeholder returns 404 until that is wired up; the CreatedAtAction URL
        // in CreateBooking will be valid from the client's perspective.
        _ = id;
        return Task.FromResult<IActionResult>(NotFound());
    }

    /// <summary>
    /// Download a confirmation artifact (PDF, QR code, or ICS) for the specified booking.
    /// AC-3: PDF downloads immediately; artifact must have been generated by the background worker.
    /// </summary>
    /// <param name="id">Appointment ID.</param>
    /// <param name="type">Artifact type: <c>pdf</c>, <c>qr</c>, or <c>ics</c>.</param>
    /// <response code="200">Artifact file returned with appropriate Content-Type.</response>
    /// <response code="400">Invalid artifact type.</response>
    /// <response code="401">JWT bearer token missing or invalid.</response>
    /// <response code="404">Artifact not yet generated or appointment not found.</response>
    [HttpGet("{id:guid}/artifacts/{type}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> DownloadArtifact(
        Guid id,
        [FromRoute] string type,
        CancellationToken ct)
    {
        var validTypes = new Dictionary<string, (string ContentType, string FileName)>(StringComparer.OrdinalIgnoreCase)
        {
            ["pdf"] = ("application/pdf",  "confirmation.pdf"),
            ["qr"]  = ("image/png",        "qrcode.png"),
            ["ics"] = ("text/calendar",    "appointment.ics")
        };

        if (!validTypes.TryGetValue(type, out var meta))
            return BadRequest("Invalid artifact type. Use: pdf, qr, ics.");

        var artifactStorage = HttpContext.RequestServices.GetRequiredService<IArtifactStorage>();

        var storagePath = $"bookings/{id}/{meta.FileName}";
        var bytes = await artifactStorage.RetrieveAsync(storagePath, ct);

        if (bytes is null)
            return NotFound("Artifact not yet generated.");

        return File(bytes, meta.ContentType, meta.FileName);
    }

    /// <summary>
    /// Cancel a confirmed appointment (AC-5).
    /// Staff may cancel within 24 hours with an override reason.
    /// Patients may not cancel within 24 hours of the appointment.
    /// </summary>
    /// <response code="200">Appointment cancelled successfully.</response>
    /// <response code="400">Invalid request or appointment cannot be cancelled.</response>
    /// <response code="403">Change not allowed within 24-hour policy window (patient).</response>
    /// <response code="404">Appointment not found.</response>
    [HttpPost("{id:guid}/cancel")]
    [ProducesResponseType(typeof(CancelBookingResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> CancelBooking(
        Guid id,
        [FromBody] CancelBookingRequest request,
        CancellationToken ct)
    {
        var userId  = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        var isStaff = User.IsInRole("Staff") || User.IsInRole("Admin");
        var result  = await _bookingService.CancelAsync(id, userId, isStaff, request, ct);

        if (result.IsSuccess)
            return Ok(result.Value);

        if (result.Error!.Contains("24 hours"))
            return StatusCode(StatusCodes.Status403Forbidden, new { message = result.Error });

        if (result.Error.Contains("not found"))
            return NotFound(new { message = result.Error });

        return BadRequest(new { message = result.Error });
    }

    /// <summary>
    /// Reschedule a confirmed appointment to a new slot (AC-5).
    /// Staff may reschedule within 24 hours with an override reason.
    /// Returns 409 if the new slot is no longer available (concurrent race).
    /// </summary>
    /// <response code="200">Appointment rescheduled successfully.</response>
    /// <response code="400">Invalid request or appointment cannot be rescheduled.</response>
    /// <response code="403">Change not allowed within 24-hour policy window (patient).</response>
    /// <response code="404">Appointment not found.</response>
    /// <response code="409">Selected slot is no longer available — choose another.</response>
    [HttpPost("{id:guid}/reschedule")]
    [ProducesResponseType(typeof(RescheduleBookingResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(SlotConflictResponse), StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> RescheduleBooking(
        Guid id,
        [FromBody] RescheduleBookingRequest request,
        CancellationToken ct)
    {
        var userId  = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
        var isStaff = User.IsInRole("Staff") || User.IsInRole("Admin");
        var result  = await _bookingService.RescheduleAsync(id, userId, isStaff, request, ct);

        if (result.IsSuccess)
            return Ok(result.Value);

        if (result.Error!.Contains("24 hours"))
            return StatusCode(StatusCodes.Status403Forbidden, new { message = result.Error });

        if (result.Error.Contains("no longer available"))
            return Conflict(new { message = result.Error });

        if (result.Error.Contains("not found"))
            return NotFound(new { message = result.Error });

        return BadRequest(new { message = result.Error });
    }
}
